<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC8-DX-3VWLX52" ignored="0" name="Test2" tests="1" failures="1" timestamp="18 Jul 2018 05:30:00 GMT" time="42.417" errors="0">
  <testcase name="method1" time="42.373" classname="program1.pgm1">
    <failure type="java.lang.AssertionError" message="expected [Sign in to GitHub. GitHub] but found [GitHub]">
      <![CDATA[java.lang.AssertionError: expected [Sign in to GitHub. GitHub] but found [GitHub]
at program1.pgm1.method1(pgm1.java:50)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
</testsuite> <!-- Test2 -->
